spring:
  application:
    name: desafio-fullstack

  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/product-sales}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update